= boot-cantaloupe project
Madrid
:icons: font
:toc: left
:sectnums:
:source-highlighter: coderay
:experimental:

NOTE: testing and tasting the Boot fruit

== JDK & friends download and installation

. Java SE Development Kit 8

.installation
 wget --no-check-certificate --no-cookies \
   --header "Cookie: oraclelicense=accept-securebackup-cookie" \
   --progress=dot:giga \
   http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
 sudo tar xvf jdk-8u131-linux-x64.tar.gz -C /usr/local/share/
 sudo ln -sf /usr/local/share/jdk1.8.0_131/bin/java /usr/local/bin/java
 java -version

. Gradle 3.5

.installation
 wget --progress=dot:giga \
   https://services.gradle.org/distributions/gradle-3.5-all.zip
 sudo unzip gradle-3.5-all.zip -d /usr/local/share/
 sudo ln -sf /usr/local/share/gradle-3.5/bin/gradle /usr/local/bin/gradle
 gradle -version

.wrapper
 gradle wrapper --gradle-version 3.5

. Maven 3.5.0

.installation
 wget --progress=dot:giga \
   http://www-us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
 sudo tar xvf apache-maven-3.5.0-bin.tar.gz -C /usr/local/share/
 sudo ln -sf /usr/local/share/apache-maven-3.5.0/bin/mvn /usr/local/bin/mvn
 mvn -v

. Ascii Art Generator