= project requirements
Madrid
:icons: font
:toc: left
:sectnums:
:source-highlighter: coderay
:experimental:

NOTE: Bajo el amparo de las iniciativas _Stop Smoke Sellers_, _Research gives you the Kempston_, _Don't warm up yourself_, _F5 Task is not enough_, _Save the yoghurts_, _Copy&Paste == time waste_ y con fines didácticos se quiere desarrollar un documento de requisitos que describe una sencilla funcionalidad empresarial.

== Resumen
Se quiere construir un Sistema de Información que permita la explotación de un Servicio de Taxi. Una vez registrados en el sistema los dos perfiles básicos, _Driver_ y _Customer_, un customer solicitará un _Journey_ a un _Driver_ para ir desde un _Point_ origen a otro destino. El _Journey_ tiene lugar a través de una _Route_ que visitará una colección de _Point_. Una vez concluido el _Journey_ se emitirá un _Receipt_ con el detalle del servicio. Tanto _Driver_ como _Customer_ disponen de varios _Profile_ que permiten personalizar la oferta y la demanda del servicio.

Por ejemplo, un cliente desea realizar un trayecto desde su domicilio al aeropuerto por la ruta más rápida disponible en el instante que solicita el servicio.

Otro ejemplo, un cliente desear realizar una carrera desde un parque en el que se encuentra con su mascota a su domicilio. Solicita el servicio a aquellos conductores que puedan ofrecerle el servicio.

== Entities
En este apartado se definen las entidades de negocio y sus atributos...

=== User
Usuario del servicio. En la primera versión podrán ser: Driver y Customer.

[cols="1,3"options="header"]
|===
|Property
|Description

|username
|nombre del usuario

|password
|clave de acceso del usuario

|registerDate
|Fecha de registro

|retry
|Número de reintentos de acceso consumidos
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|person
|es una persona

|*profile*
|*tiene 1 perfil (TODO)*

|*payment method*
|*tiene N métodos de pago (TODO)*
|===

=== Driver
Conductor de un vehículo que transporta a un cliente desde un lugar a otro.

[cols="1,3"options="header"]
|===
|Property
|Description

|available
|disponibilidad del conductor
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|user
|es un usuario

|vehicle
|conduce 1 coche
|===

=== Customer
Persona que contrata un trayecto de taxi. El cliente que contrata el trayecto puede ser distinto a la persona transportada.

[cols="1,3"options="header"]
|===
|Property
|Description
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|user
|es un usuario
|===

=== Profile
[red]#TODO:# Serviría por ejemplo para filtrar la colección de vehículos que se muestran a un cliente cuando solicita un trayecto.

=== PaymentMethod
[red]#TODO:# Serviría para incicar los metodos de pago disponibles.

=== Person
Persona Física que representa a un usuario del sistema.

[cols="1,3"options="header"]
|===
|Property
|Description

|name
|nombre del cliente

|surname
|Apellidos del cliente

|email
|correo electrónico

|phone
|Teléfono del cliente

|postalCode
|Código postal

|address
|Dirección del cliente

|city
|Ciudad del cliente
|===

=== Vehicle
Vehículo con el que el conductor presta el servicio a un  cliente.

[cols="1,3"options="header"]
|===
|Property
|Description

|plate
|matrícula del vehículo

|brand
|marca del vehículo

|description
|descripción detallada del vehículo
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|driver
|es conducido por 1 conductor
|===

=== Journey
Representa el trayecto o viaje solicitado por el cliente.

[cols="1,3"options="header"]
|===
|Property
|Description
|alias
|Identificador del trayecto
|requestAccepted
|Indicador de solicitud aceptada por el Driver
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|request
|Driver solicitado

|origin
|Punto de partida del trayecto

|destiny
|Punto destino del trayecto
|===

=== Point
Punto de coordenadas terrestre formado por longitude y latitude por el que discurre el viaje o trayecto.

[cols="1,3"options="header"]
|===
|Property
|Description

|latitude
|Latitud geográfica

|longitude
|Longitud geográfica
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|route
|forma parte de 1 ruta
|===

=== Route
Colección de puntos que recorre el taxi para prestar el servicio.

[cols="1,3"options="header"]
|===
|Property
|Description

|points
|Lista de puntos geográficos que definen la trayectoria
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|footprint
|está formada por n huellas
|===

=== Footprint o track
Point ubicado en el tiempo. Una colección de footprints forma una ruta.

[cols="1,3"options="header"]
|===
|Property
|Description

|point
|Punto geográfico

|datetime
|Fecha y hora del punto sobre la trayectoria
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|point
|Está asociada a 1 punto geográfico de la trayectoria

|route
|forman parte de 1 ruta
|===

== Business rules
[red]#TODO# En este apartado se definen las reglas de negocio que incluyen las validaciones, reglas simples y reglas compuestas por otras reglas...

. Definir la política de asignación de un trayecto a un conductor
. Definir la política de cancelación de un trayecto para un conductor. Definir la política de penalización.
. Definir la política de cancelación de un trayecto para un cliente
. Definir la política de puntos para un conductor. Definir la política de penalización para puntuación igual a cero.
. Definir la política para el cálculo de la tarifa de un trayecto
. Definir la política para mostrar un vehículo disponible

=== FareService
Define la lógica necesaria para cancelar el trayecto y emitir la factura.

=== LocatorService
Define la lógica necesaria para localizar los vehículos.

=== RankingService
Define la lógica necesaria para la valoración y bonificación de conductores y usuarios.

Por ejemplo, un conductor recibe puntos/bonificación por haber devuelto la documentación a un cliente que notificó a Atención al Cliente haberla olvidado en el vehículo.


=== PaymentService

== Use Cases

=== Registro conductor en la aplicación
[red]#TODO# 

=== Registro cliente en la aplicación
[red]#TODO# 

=== Login de usuario
. El usuario (conductor/cliente) debe estar previamente registrado

=== Solicitar un trayecto por un cliente
. El cliente se autentica en la aplicación
. Se obtiene la posición actual del cliente
. Se solicita el destino
. Se muestra propuesta de vehículos disponibles
. El cliente elige el vehículo para viajar
. El cliente recibe notificación de solicitud aceptada

=== Esperando a ser recogido
. El cliente ha recibido una notificación de solicitud aceptada previamente
. El cliente podrá visualizar durante ese tiempo de espera la posición actual del vehículo elegido

=== Activar disponibilidad por un conductor
. El conductor se muestra como disponible marcándolo desde la aplicación y los clientes lo visualizarán como opción posible.

=== Desactivar disponibilidad por un conductor
. El conductor se marca como no disponible desde la aplicación y los clientes no lo visualizarán como opción

=== Iniciar un trayecto por un conductor
. El conductor recibe una notificación de solicitud de carrera
. El conductor acepta la solicitud y comienza la espera por parte el cliente

=== Finalizar un trayecto por un conductor
. El conductor llega al destino solicitado por el cliente
. El conductor notifica a través de la aplicación que ha llegado a destino
. La aplicación emite la factura correspondiente

=== Cancelar un trayecto por un conductor
. El conductor no puede atender la petición una vez ya ha sido aceptada previamente y por tanto la cancela.
. El conductor debe seleccionar un motivo para la cancelación del trayecto.

=== Cancelar un trayecto por un cliente
. El cliente podrá cancelar el viaje por coste de cero euros si el conductor no ha iniciado su carrera
. En el caso de que el conductor haya iniciado su carrera se le cobrará un recargo de 5 euros

=== Puntuar a un Conductor
[red]#TODO# 

=== Mostrar la lista de trayectos
. El cliente podrá en cualquier momento visualizar un historial de trayectos que haya realizado con anterioridad.

Se permite un filtro sencillo con rango de fechas.

=== Calcular la factura final de un trayecto
. El cálculo de la factura será el número de Km's multiplicado por la tarifa que aplique dependiendo del vehículo elegido

. [red]#TODO# El cálculo de la factura será el número de Km's multiplicado por la tarifa que aplique al perfil del cliente y dependiendo del perfil del vehículo elegido

=== Enviar la factura de un trayecto
. Si se ha cancelado por parte del cliente se emite factura de X euros.
. [red]#TODO# Si se ha concluido el trayecto satisfactoriamente se emite factura del precio aplicado al perfil del cliente y dependiendo del perfil del vehículo elegido

=== PaymentMethod
[red]#TODO# Medio de pago por el que los usuarios del sistema abonan los conceptos del servicio.

==== CreditCard

=== Receipt
[red]#TODO# Factura correspondiente al servicio prestado.
