= project requirements
Madrid
:icons: font
:toc: left
:sectnums:
:source-highlighter: coderay
:experimental:

NOTE: Bajo el amparo de las iniciativas _Stop Smoke Sellers_, _Research gives you the Kempston_, _Don't warm up yourself_, _F5 Task is not enough_, _Save the yoghurts_, _Copy&Paste == time waste_ y con fines didácticos se quiere desarrollar un documento de requisitos que describe una sencilla funcionalidad empresarial.

== Resumen
Se quiere construir un Sistema de Información que permita la explotación de un Servicio de Taxi. Una vez registrados en el sistema los dos perfiles básicos, _Driver_ y _Customer_, un customer solicitará un _Journey_ a un _Driver_ para ir desde un _Point_ origen a otro destino. El _Journey_ tiene lugar a través de una _Route_ que visitará una collección de _Point_. Una vez concluido el _Journey_ se emitirá un _Receipt_ con el detalle del servicio. Tanto _Driver_ como _Customer_ disponen de varios _Profile_ que permiten personalizar la oferta y la demanda del servicio.

Por ejemplo, un cliente desea realizar un trayecto desde su domicilio al aeropuerto por la ruta más rápida disponible en el instante que solicita el servicio.

Otro ejemplo, un cliente desear realizar una carrera desde un parque en el que se encuentra con su mascota a su domicilio. Solicita el servicio a aquellos conductores que puedan ofrecerle el servicio.

== Entities (TODO)
En este apartado se definien las entidades de negocio y sus atributos...

=== User (TODO)
Usuario del servicio. En la primera versión podrán ser: Conductor y Cliente.

[cols="1,3"options="header"]
|===
|Property
|Description

|name
|nombre del usuario

|email
|correo electrónico
|===

[cols="1,3"options="header"]
|===
|Relationship
|Description

|profile
|tiene 1 perfil

|payment method
|tiene N métodos de pago
|===

=== Driver (TODO)
Conductor de un vehículo que transporta a un cliente desde un lugar a otro.

=== Customer (TODO)
Persona que contrata un trayecto de taxi. El cliente que contrata el trayecto puede ser distinto a la persona transportada.

=== Profile  (TODO)
TODO

=== Persona
Persona Física que representa a un usuario del sistema.

=== Vehicle
Vehículo con el que el conductor presta el servicio a un  cliente.

=== Journey (TODO)
Representa el trayecto o viaje solicitado por el cliente.

=== Point (TODO)
Punto de coordenadas terrestre formado por longitude y latitude por el que discurre el viaje o trayecto.

=== Route (TODO)
Colección de puntos que recorre el taxi para prestar el servicio.

=== PaymentMethod (TODO)
Medio de pago por el que los usuarios del sistema abonan los conceptos del servicio.

==== CreditCard

=== Receipt (TODO)
Factura correspondiente al servicio prestado.

== Business rules (TODO)
En este apartado se definen las reglas de negocio que incluyen las validaciones, reglas simples y reglas compuestas por otras reglas...

. Definir la política de asignación de un trayecto a un conductor
. Definir la política de cancelación de un trayecto para un conductor. Definir la política de penalización.
. Definir la política de cancelación de un trayecto para un cliente
. Definir la política de puntos para un conductor. Definir la política de penalización para puntuación igual a cero.
. Definir la política para el cálculo de la tarifa de un trayecto
. Definir la política para mostrar un vehículo disponible

== Use Cases

=== Registro conductor en la aplicación (TODO)

=== Registro cliente en la aplicación (TODO)

=== Login de usuario
. El usuario (conductor/cliente) debe estar previamente registrado

=== Solicitar un trayecto por un cliente
. El cliente se loga en la aplicación
. Se obtiene la posición actual del cliente
. Se solicita el destino
. Se muestra propuesta de vehículos disponibles
. El cliente elige el vehículo para viajar
. El cliente recibe notificación de solicitud aceptada

=== Esperando a ser recogido
. El cliente ha recibido una notificación de solicitud aceptada previamente
. El cliente podrá visualizar durante ese tiempo de espera la posición actual del vehículo elegido

=== Iniciar un trayecto por un conductor
. El conductor recibe una notificación de solicitud de carrera
. El conductor acepta la solicitud y comienza la espera por parte el cliente

=== Finalizar un trayecto por un conductor
. El conductor llega al destino solicitado por el cliente
. El conductor notifica a través de la aplicación que ha llegado a destino
. La aplicación emite la factura correspondiente

=== Cancelar un trayecto por un conductor


=== Cancelar un trayecto por un cliente
. El cliente podrá cancelar el viaje por coste de cero euros si el conductor no ha iniciado su carrera
. En el caso de que el conductor haya iniciado su carrera se le cobrará un recargo de 5 euros

=== Puntuar a un Conductor


=== Mostrar la lista de trayectos
. El cliente podrá en cualquier momento visualizar un historial de trayectos que haya realizado con anterioridad

=== Enviar la factura de un trayecto
. Si se ha cancelado por parte del cliente se emite factura de X euros
. Si se ha concluído el trayecto satisfactoriamente se emite factura del precio aplicado al perfil del cliente y dependiendo del perfil del vehículo elegido